# Change these first
owner: yasan.dev # Your GitHub organization or username, where this repository lives
repo: status.yasan.dev # The name of this repository

sites:
  - name: Toronto Server
    url: https://www.yasan.dev
    icon: https://yasan.dev/Upptime/toronto-server.png
    assignees:
      - yasandev

status-website:
  themeUrl: https://yasan.dev/Upptime/upptime.css
  cname: status.yasan.dev
  logoUrl: https://yasan.dev/Upptime/logo.png
  name: YASAN Status
  favicon: https://yasan.dev/favicon.png
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
